name: Auto Fix Code Issues

on:
  pull_request:
    branches: [dev]
    types: [synchronize, opened, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-fix:
    # Only run if this is a PR targeting dev
    if: github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check for formatting issues
        id: check-format
        run: |
          if pnpm format:check; then
            echo "format_needed=false" >> $GITHUB_OUTPUT
          else
            echo "format_needed=true" >> $GITHUB_OUTPUT
          fi

      - name: Check for linting issues
        id: check-lint
        run: |
          if pnpm lint; then
            echo "lint_needed=false" >> $GITHUB_OUTPUT
          else
            echo "lint_needed=true" >> $GITHUB_OUTPUT
          fi

      - name: Auto format
        if: steps.check-format.outputs.format_needed == 'true'
        run: pnpm format

      - name: Auto fix linting issues
        if: steps.check-lint.outputs.lint_needed == 'true'
        run: pnpm lint:fix

      - name: Check for changes
        id: check-changes
        if: |
          steps.check-format.outputs.format_needed == 'true' ||
          steps.check-lint.outputs.lint_needed == 'true'
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git
        if: |
          (steps.check-format.outputs.format_needed == 'true' ||
           steps.check-lint.outputs.lint_needed == 'true') &&
          steps.check-changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push fixes
        if: |
          (steps.check-format.outputs.format_needed == 'true' ||
           steps.check-lint.outputs.lint_needed == 'true') &&
          steps.check-changes.outputs.has_changes == 'true'
        run: |
          git add -A
          git commit -m "style: auto-fix code formatting and linting issues

          This commit was automatically created to fix issues detected by the CI workflow.

          - Applied Prettier formatting fixes
          - Applied ESLint auto-fixes
          - No functional changes, only code quality improvements

          🤖 Generated with [Claude Code](https://claude.ai/code)"
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git push origin HEAD:${{ github.event.pull_request.head.ref }} --force-with-lease